# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /accounts/{accountId}/details_get for http method type GET 
# RoostTestHash=6ef676878c
# 
# 

# ********RoostGPT********
Feature: Accounts Details API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Get account details with valid input
    Given path '/accounts/<accountId>/details'
    And header Authorization = '<Authorization>'
    And header uuid = '<uuid>'
    And header Accept = '<Accept>'
    And header client_id = '<client_id>'
    And header countryCode = '<countryCode>'
    When method get
    Then status <status>
    And match response == <response>

    Examples:
      | accountId | Authorization  | uuid   | Accept             | client_id   | countryCode | status | response                                                                                                                                                                                                                                                                                                           |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    200 | { "fullName": "John Doe", "firstName": "John", "lastName": "Doe", "emails": [ { "emailAddress": "john.doe@example.com", "preferenceType": "PRIMARY" } ], "addressList": [ { "addressId": "1", "countryCode": "US", "postalCode": "12345" } ], "phones": [ { "phoneType": "HOME", "preferenceType": "PRIMARY" } ] } |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    400 | { "error": {}, "error_description": {}, "type": {}, "code": {}, "details": {} }                                                                                                                                                                                                                                    |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    401 | { "error": {}, "error_description": {}, "type": {}, "code": {}, "details": {} }                                                                                                                                                                                                                                    |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    403 | { "error": {}, "error_description": {}, "type": {}, "code": {}, "details": {} }                                                                                                                                                                                                                                    |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    404 | { "type": {}, "code": {}, "details": {} }                                                                                                                                                                                                                                                                          |
      |       123 | 'Bearer token' | '1234' | 'application/json' | 'client123' | 'US'        |    500 | { "type": {}, "code": {}, "details": {} }                                                                                                                                                                                                                                                                          |
