# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: API Tests for /2.1/laureate/{laureateID}

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Verify successful response for valid laureate ID
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.laureateIfPerson.knownName.en == '#string'
    And match response.laureate.laureateIfPerson.givenName.en == '#string'
    And match response.laureate.laureateIfPerson.familyName.en == '#string'
    And match response.laureate.laureateIfPerson.birth.date == '#string'
    And match response.laureate.laureateIfPerson.birth.place.city.en == '#string'
    And match response.laureate.laureateIfPerson.gender == '#string'
    And match response.laureate.laureateIfOrg.orgName.en == '#string'
    And match response.laureate.laureateIfOrg.nativeName == '#string'
    And match response.laureate.laureateIfOrg.founded.date == '#string'

    Examples:
      | read('laureate_laureateID_get.csv') |

  Scenario Outline: Verify response for invalid laureate ID
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 404
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      |         -1 |
      |          0 |

  Scenario Outline: Verify malformed syntax response
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      | abc        |
      | invalid    |

  Scenario Outline: Verify unprocessable entity response
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 422
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | laureateID |
      |      12345 |
      |      67890 |

  Scenario Outline: Verify response headers for valid laureate ID
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | read('laureate_laureateID_get.csv') |
