# ********RoostGPT********

# Test generated by RoostGPT for test api-karate-petstore-v3_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /ping_get for http method type GET 
# RoostTestHash=4a0ae9dcca
# 
# 

# ********RoostGPT********
Feature: Ping Server

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Ping the server
    Given path '/ping'
    When method GET
    Then status 200
    And match response.message == '#string'
    And match response.message contains 'pong'

    Examples:
      | read('ping_get.csv') |
