
// ********RoostGPT********
/*

# Test generated by RoostGPT for test api-karate-petstore-v3_clone using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /ping_get for http method type GET 
# RoostTestHash=4a0ae9dcca
# 
# 

roost_feedback [02/07/2025, 2:54:07 AM]:-\sAdd\smore\scomments\sto\sthe\stest
*/

// ********RoostGPT********

Feature: Ping Server

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Ping the server
    Given path '/ping'
    When method GET
    Then status 200
    And match response.message == '#string'
    And match response.message contains 'pong'

    Examples:
      | read('ping_get.csv') |
********RoostGPT********
Feature: Ping Server

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Ping the server
    Given path '/ping' # Set the path to the ping endpoint
    When method GET # Send a GET request to the ping endpoint
    Then status 200 # Verify that the response status is 200
    And match response.message == '#string' # Verify that the response message is a string
    And match response.message contains 'pong' # Verify that the response message contains 'pong'

    Examples:
      | read('ping_get.csv') | # Read test data from ping_get.csv file
