# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
Feature: Get Employee by ID

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Validate successful retrieval of an employee by ID
    Given path 'employees', '<id>'
    When method get
    Then status 200
    And match response ==
      """
      {
        "id": "#string",
        "jobTitle": "#string",
        "name": "#string",
        "email": "#string"
      }
      """
    And match response.id == '<id>'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'

    Examples:
      | read('employees_id_get.csv') |

  Scenario Outline: Validate error response when employee ID is not found
    Given path 'employees', '<id>'
    When method get
    Then status 404

    Examples:
      | id                                     |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0853' |
      | 'd290f1ee-6c54-4b01-90e6-d701748f0854' |
