# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=e5b9d8d67f
# 
# 

# ********RoostGPT********
Feature: Employee API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Add Employee
    Given path '/employees'
    And request
      """
      {
        "id": "<id>",
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
      """
    When method post
    Then status <status>
    And match response.id == '#string'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'

    Examples:
      | id                                   | jobTitle       | name       | email                    | status |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst | John Smith | john.smith@acme-corp.com |    201 |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst | John Smith | john.smith@acme-corp.com |    409 |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst | John Smith | invalid-email            |    400 |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst | John Smith |                          |    400 |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst |            | john.smith@acme-corp.com |    400 |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 |                | John Smith | john.smith@acme-corp.com |    400 |
