# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=e5b9d8d67f
# 
# 

# ********RoostGPT********
Feature: Employee API Tests
  Description: Comprehensive tests for the employee API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Add a new employee successfully (POST /employees)
    Given path 'employees'
    And request """ 
      { 
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
    """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.id == '#string'
    And match response.id == '#uuid'
    And match response.jobTitle == '#string'
    And match response.name == '#string'
    And match response.email == '#string'
    And match response.path == 'employees'

    Examples:
      | jobTitle         | name         | email                      |
      | System Analyst   | John Smith   | john.smith@acme-corp.com   |

  Scenario Outline: Invalid input data for employee creation (POST /employees)
    Given path 'employees'
    And request """ 
      { 
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
    """
    When method POST
    Then status 400

    Examples:
      | jobTitle         | name         | email     |
      | null             | John Smith   | invalid   |
      | System Analyst   | null         | null      |
      | ""               | ""           | ""        |

  Scenario Outline: Conflict when adding an existing employee (POST /employees)
    Given path 'employees'
    And request """
      { 
        "jobTitle": "<jobTitle>",
        "name": "<name>",
        "email": "<email>"
      }
    """
    When method POST
    Then status 409

    Examples:
      | jobTitle       | name       | email                    |
      | System Analyst | John Smith | john.smith@acme-corp.com |
