# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=48e4dd6cd8
# 
# 

# ********RoostGPT********
Feature: Employee API Validation

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario: Validate GET /employees endpoint with no searchString
    Given path 'employees'
    When method GET
    Then status 200
    And match response == '#[]'
    And match response == '#array'

  Scenario Outline: Validate GET /employees endpoint with searchString
    Given path 'employees'
    And param searchString = <searchString>
    When method GET
    Then status 200
    And match response == '#array'
    And match response[*].id == '#string'
    And match response[*].jobTitle == '#string'
    And match response[*].name == '#string'
    And match response[*].email == '#string'

    Examples:
      | read('employees_get.csv') |

  Scenario: Validate GET /employees endpoint with invalid query parameter
    Given path 'employees'
    And param search = 'randomValue'
    When method GET
    Then status 400

  Scenario: Validate response headers for GET /employees endpoint
    Given path 'employees'
    When method GET
    Then status 200
    And match responseHeaders.Content-Type == 'application/json'
