# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=0a005b8a0e
# 
# 

# ********RoostGPT********
Feature: Employee API - Get Employee By ID

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Retrieve an Employee with a Valid ID
    Given path '/employees/<id>'
    When method GET
    Then status 200
    And match response == """
    {
      id: '#string',
      jobTitle: '#string',
      name: '#string',
      email: '#string'
    }
    """

    Examples:
      | id                                   |
      | d290f1ee-6c54-4b01-90e6-d701748f0851 |

  Scenario Outline: Employee Not Found with Invalid ID
    Given path '/employees/<id>'
    When method GET
    Then status 404

    Examples:
      | id                                   |
      | 00000000-0000-0000-0000-000000000000 |
