# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /icd/s2s/exchange/refundMessage_post for http method type POST 
# RoostTestHash=eeed01c3dd
# 
# 

# ********RoostGPT********
Feature: Refund Message API

Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

Scenario Outline: Test POST /icd/s2s/exchange/refundMessage with valid input
    Given path '/icd/s2s/exchange/refundMessage'
    And request
    """
    {
        "messageHeader": {
            "headerVersion": "<headerVersion>",
            "timestamp": "<timestamp>",
            "sourceContext": {
                "sourceId": "<sourceId>",
                "applicationId": "<applicationId>",
                "transactionId": "<transactionId>"
            },
            "messageContext": {
                "messageContentType": "<messageContentType>",
                "messageContentEncoding": "<messageContentEncoding>",
                "payloadHashValue": "<payloadHashValue>",
                "hashingAlgorithm": "<hashingAlgorithm>"
            },
            "multiPartMessageContextTypes": [
                {
                    "messageCorrelationContext": "<messageCorrelationContext>",
                    "messageCorrelationId": "<messageCorrelationId>",
                    "messageSequenceNumber": "<messageSequenceNumber>",
                    "messageSequenceSize": "<messageSequenceSize>"
                }
            ]
        },
        "augmentationPoint": [
            {
                "augmentationKey": "<augmentationKey>",
                "augmentationValue": "<augmentationValue>"
            }
        ],
        "payload": {
            "refundTransactions": {
                "remark": "<remark>",
                "documentNumber": "<documentNumber>",
                "refundedCoupons": [
                    "<refundedCoupon>"
                ],
                "issuanceDate": "<issuanceDate>",
                "refundIndicator": "<refundIndicator>",
                "refundUID": "<refundUID>",
                "relatedRefundUID": "<relatedRefundUID>",
                "oadCode": "<oadCode>"
            },
            "refundingAgentDetails": {
                "cityPointOfSale": "<cityPointOfSale>",
                "areaPointOfSale": "<areaPointOfSale>",
                "countryPointOfSale": "<countryPointOfSale>",
                "issuerSystem": "<issuerSystem>"
            },
            "monetaryInformation": {
                "refundedFormOfPayment": [
                    {
                        "fopType": "<fopType>",
                        "amount": {
                            "amount": <amount>,
                            "currency": "<currency>"
                        },
                        "refundedCardDetails": {
                            "maskedCardNumber": "<maskedCardNumber>",
                            "vendorCode": "<vendorCode>",
                            "binNumber": "<binNumber>",
                            "lastFour": "<lastFour>"
                        },
                        "refundedFare": {
                            "amount": <refundedFareAmount>,
                            "currency": "<refundedFareCurrency>"
                        },
                        "refundFee_CancellationPenality": {
                            "amount": <refundFeeCancellationPenalityAmount>,
                            "currency": "<refundFeeCancellationPenalityCurrency>"
                        },
                        "refundFee_TaxOnCancellationPenality": {
                            "amount": <refundFeeTaxOnCancellationPenalityAmount>,
                            "currency": "<refundFeeTaxOnCancellationPenalityCurrency>",
                            "taxISOCode": "<taxISOCode>",
                            "taxCityCode": "<taxCityCode>"
                        },
                        "refundedFee": {
                            "amount": <refundedFeeAmount>,
                            "currency": "<refundedFeeCurrency>"
                        },
                        "refundedTax": {
                            "amount": <refundedTaxAmount>,
                            "currency": "<refundedTaxCurrency>",
                            "taxISOCode": "<refundedTaxISOCode>",
                            "taxCityCode": "<refundedTaxCityCode>"
                        }
                    }
                ]
            }
        }
    }
    """
    When method post
    Then status 200
    And match response == '#string'
    And match response == 'icd/s2s/exchange/refundMessage'

    Examples:
    | headerVersion | timestamp         | sourceId | applicationId | transactionId | messageContentType | messageContentEncoding | payloadHashValue | hashingAlgorithm | messageCorrelationContext | messageCorrelationId | messageSequenceNumber | messageSequenceSize | augmentationKey | augmentationValue | remark | documentNumber | refundedCoupon | issuanceDate | refundIndicator | refundUID | relatedRefundUID | oadCode | cityPointOfSale | areaPointOfSale | countryPointOfSale | issuerSystem | fopType | amount | currency | maskedCardNumber | vendorCode | binNumber | lastFour | refundedFareAmount | refundedFareCurrency | refundFeeCancellationPenalityAmount | refundFeeCancellationPenalityCurrency | refundFeeTaxOnCancellationPenalityAmount | refundFeeTaxOnCancellationPenalityCurrency | taxISOCode | taxCityCode | refundedFeeAmount | refundedFeeCurrency | refundedTaxAmount | refundedTaxCurrency | refundedTaxISOCode | refundedTaxCityCode |
    | 1.0           | 2023-10-01T12:00:00Z | 123456   | 654321       | 987654321     | application/json  | UTF-8              | abcdef1234567890    | SHA-256          | correlationContext1  | correlationId1    | 1                  | 1                  | key1            | value1           | remark1| doc1234567890   | coupon1         | 2023-09-01       | true             | uid1234567890    | relatedUid1234567890 | oad1234567890   | NYC            | NYC            | US               | issuer1         | CC             | 100.00          | USD              | 1234********1234  | vendor1         | 123456          | 1234            | 50.00            | USD              | 20.00            | USD              | 10.00            | USD              | US              | NYC             | 15.00            | USD              | US              | NYC             |
