# ********RoostGPT********

# Test generated by RoostGPT for test api-karate-petstore-v3_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=1225a4a07f
# ROOST_METHOD_SIG_HASH=3a429a7e0a
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\r\n' +
#     '  As a user of the Credential Wallet API\r\n' +
#     '  I want to be able to perform CRUD operations on accounts\r\n' +
#     '  So that I can manage my account effectively',
#   background: 'Background:\r\n    Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Create my account',
#     steps: 'When the client sends a POST request "/accounts" with the accounts_body payload\r\n' +
#       'Then create an account with the specified informatio\r\n' +
#       'And verify the account created using GET request for "/me"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to be able to perform CRUD operations on accounts
  So that I can manage my account effectively

  Background:
    * url 'http://localhost:8080'

  Scenario: Create a new account
    Given path '/accounts'
    And request """ 
      {
        "name": "John Doe",
        "email": "john.doe@example.com",
        "password": "securePassword123"
      }
    """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "id": "#string",
        "name": "John Doe",
        "email": "john.doe@example.com",
        "password": null,
        "created_at": "#string"
      }
      """

  Scenario: Verify created account details
    Given path '/me'
    When method GET
    Then status 200
    And match response ==
      """
      {
        "id": "#string",
        "name": "John Doe",
        "email": "john.doe@example.com"
      }
      """
