# ********RoostGPT********

# Test generated by RoostGPT for test api-karate-petstore-v3_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# ROOST_METHOD_HASH=411b891724
# ROOST_METHOD_SIG_HASH=536a03cafe
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\r\n' +
#     '  As a user of the Credential Wallet API\r\n' +
#     '  I want to be able to perform CRUD operations on accounts\r\n' +
#     '  So that I can manage my account effectively',
#   background: 'Background:\r\n    Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Grant authorization',
#     steps: 'Given an existing account, create another account\r\n' +
#       'When the client sends a POST request to "/authorizations"\r\n' +
#       'Then grant access to your account and confirm access via GET request to "/authorizations"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to be able to perform CRUD operations on accounts
  So that I can manage my account effectively

  Background:
    * url 'http://localhost:8080'

  Scenario: Grant authorization
    Given path '/authorizations'
    And configure headers =
      """
      { 
        "Authorization": "#(karate.properties['AUTH_TOKEN'])" 
      }
      """
    And def requestPayload =
      """
      {
        "accountId": 123,
        "authorizedAccountId": 456
      }
      """
    When method POST
    And request requestPayload
    Then status 201
    And match response == '#object'
    And match response.accountId == '#number'
    And match response.authorizedAccountId == '#number'

  Scenario: Validate access confirmation via GET request
    Given path '/authorizations'
    And configure headers =
      """
      { 
        "Authorization": "#(karate.properties['AUTH_TOKEN'])" 
      }
      """
    When method GET
    Then status 200
    And match response == '#[]'
    And match response contains
      """
      {
        "accountId": 123,
        "authorizedAccountId": 456
      }
      """
