# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Test /example endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario: Test GET /example endpoint
    Given path '/example'
    When method GET
    Then status 200
    And match response == { response: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Test POST /example endpoint
    Given path '/example'
    And request { request: '#string' }
    When method POST
    Then status 200
    And match response == { response: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Test PUT /example endpoint
    Given path '/example'
    And request { request: '#string' }
    When method PUT
    Then status 200
    And match response == { response: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Test DELETE /example endpoint
    Given path '/example'
    When method DELETE
    Then status 200
    And match response == { response: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'
