# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Example API Test
  This feature file tests the 'example' endpoint for different request methods, parameters, and response properties.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario: Verify GET method for /example endpoint
    Given path 'example'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.data == '#object'
    And match response.data.id == '#number'
    And match response.data.name == '#string'

  Scenario Outline: Verify GET method with parameters for /example endpoint
    Given path 'example'
    And param 'id' = <id>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.data.id == <id>
    And match response.data.name == '#string'

    Examples:
      | id |
      |  1 |
      |  2 |

  Scenario: Verify POST method for /example endpoint with valid payload
    Given path 'example'
    And request """ 
    {
      "name": "Test Name",
      "description": "Test Description"
    }
    """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.data.id == '#number'
    And match response.data.name == 'Test Name'
    And match response.data.description == 'Test Description'

  Scenario: Verify PUT method for /example endpoint with valid payload
    Given path 'example'
    And request """ 
    {
      "id": 1,
      "name": "Updated Name",
      "description": "Updated Description"
    }
    """
    When method PUT
    Then status 200
    And match response == '#object'
    And match response.data.id == 1
    And match response.data.name == 'Updated Name'
    And match response.data.description == 'Updated Description'

  Scenario: Verify DELETE method for /example endpoint
    Given path 'example'
    And param 'id' = 1
    When method DELETE
    Then status 204
