# ********RoostGPT********

# Test generated by RoostGPT for test api-swagger using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /ping_get for http method type GET 
# RoostTestHash=628b0897a0
# 
# 

# ********RoostGPT********
Feature: Ping Endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario: Verify Ping Endpoint
    Given path '/ping'
    When method get
    Then status 200
    And match response == { "message": "#string" }
