# ********RoostGPT********

# Test generated by RoostGPT for test swagger-api-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /ping_get for http method type GET 
# RoostTestHash=628b0897a0
# 
# 

# ********RoostGPT********
Feature: Validate the /ping endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario: Validate the server heartbeat operation with GET request
    Given path 'ping'
    When method GET
    Then status 200
    And match response == '''
    #string
    '''

  Scenario: Validate response headers for the /ping endpoint
    Given path 'ping'
    When method GET
    Then status 200
    And match responseHeaders == '''
    #notnull
    '''
    And match responseHeaders['Content-Type'] contains 'text/plain'

  Scenario Outline: Validate /ping endpoint with various authorization tokens
    Given path 'ping'
    And header Authorization = """
    <token>
    """
    When method GET
    Then status 200
    And match response == '''
    #string
    '''

    Examples:
      | token           |
      | Bearer token1    |
      | Bearer token2    |
      | Bearer token3    |
